---
- name: Set app template
  set_fact:
    template_split: "{{ env_definition['envTemplate']['artifact'] | split(':') }}"
    ignore_errors: True

- name: Set path without extension to a configuration file
  set_fact:
    config_file_path: "{{ base_dir + '/configuration/artifact_definitions/' + template_split[0] }}"

- name: Determine whether configuration file has .yaml or .yml extension and add it to a variable
  set_fact:
    config_file_path: "{{ (config_file_path + '.yaml' if lookup('file', config_file_path + '.yaml', errors='ignore') is not none else config_file_path + '.yml')}}"

- name: Include vars from configuration file
  set_fact:
    configs: "{{ lookup('file', config_file_path) | from_yaml }}"
    ignore_errors: True

- name: Validate username and password
  ansible.builtin.fail:
    msg:  "username or password for registry '{{ configs['registry']['name'] }}' is null.
    Set registry username and password in the '{{ configs['registry']['credentialsId'] }}' credential located in the file /configuration/credentials/credentials.yml"
  when: cred_config[configs['registry']['credentialsId']]['data']['username'] == None or cred_config[configs['registry']['credentialsId']]['data']['password'] == None

- name: Set username, password
  set_fact:
    repository_username: "{{ cred_config[configs['registry']['credentialsId']]['data']['username'] }}"
    repository_password: "{{ cred_config[configs['registry']['credentialsId']]['data']['password'] }}"
  no_log: false

- name: Run maven discovery repository
  maven_artifact:
    discovery_repository: "true"
    artifact_definition: "{{ configs }}"
    version: "{{ template_split[1] }}"
    username: "{{ repository_username }}"
    password: "{{ repository_password }}"
    extension: json
  no_log: false
  register: discovery_output
  when:
    - not (env_definition.envTemplate.artifactIsZip | default(false) | bool)

- name: Set app template
  set_fact:
    group_id: "{{ configs['groupId'] }}"
    artifact_id: "{{ configs['artifactId'] }}"
    version: "{{ template_split[1] }}"
    repository_url: "{{ discovery_output.repository_url | default(configs['registry']['mavenConfig']['repositoryDomainName']) }}"
