---
- name: Download an artifact using Artifactory username/password
  community.general.maven_artifact:
    group_id:     "{{ group_id }}"
    artifact_id:  "{{ artifact_id }}"
    version:      "{{ version }}"
    repository_url: "{{ repository_url }}"
    username:       "{{ repository_username }}"
    password:       "{{ repository_password }}"
    dest:           "{{ dd_dest }}"
    extension: json
  when: not (env_definition.envTemplate.artifactIsZip | default(false) | bool)

- name: Run maven artifact to find artifact version
  maven_artifact:
    group_id:       "{{ group_id }}"
    artifact_id:    "{{ artifact_id }}"
    version:        "{{ version }}"
    repository_url: "{{ repository_url }}"
    username:       "{{ repository_username }}"
    password:       "{{ repository_password }}"
    dest:           "{{ dd_dest }}"
    extension: json
  no_log: false
  when:
    - version is search('SNAPSHOT')
    - not (env_definition.envTemplate.artifactIsZip | default(false) | bool)
  register: module_output

- debug:
    var: module_output.version_dd
  when:
    - version is search('SNAPSHOT')
    - not (env_definition.envTemplate.artifactIsZip | default(false) | bool)

- name: Set artifact version from snapshot
  set_fact:
    atrifact_latest_version: "{{ module_output.version_dd  | default(version) }}"
  when: not (env_definition.envTemplate.artifactIsZip | default(false) | bool)

- name: Lookup artifact version from downloaded artifact
  set_fact:
    atrifact_name_list: "{{ lookup('file',lookup('ansible.builtin.vars','dd_dest')) | from_json | json_query('configurations[0].artifacts[0].id')| split(':') }}"
  when: not (env_definition.envTemplate.artifactIsZip | default(false) | bool)

- name: Lookup template repository from downloaded artifact
  set_fact:
    template_repository_url: "{{ (lookup('file',lookup('ansible.builtin.vars','dd_dest')) | from_json | json_query('configurations[0].maven_repository')) or repository_url }}"
  when:
    - env_definition['envTemplate']['artifact'] is defined
    - not (env_definition.envTemplate.artifactIsZip | default(false) | bool)


- name: Download a real artifact using Artifactory username/password
  community.general.maven_artifact:
    group_id:       "{{ atrifact_name_list[0] | default(group_id) }}"
    artifact_id:    "{{ atrifact_name_list[1] | default(artifact_id) }}"
    version:        "{{ atrifact_name_list[2] | default(version)  }}"
    repository_url: "{{ template_repository_url | default(repository_url) }}"
    username:       "{{ repository_username }}"
    password:       "{{ repository_password }}"
    dest:           "{{ artifact_dest }}"
    extension: zip

- name: Unpack an artifact
  unarchive:
    src: "{{ artifact_dest }}"
    dest: "{{ build_env_path }}"
