---
- name: Get profile template name from {{ profile.template_path }}
  set_fact:
    _profile_template_name: "{{ profile.template_path.split('/')|last|replace('.yml.j2', '')|replace('.yaml.j2', '') }}"

- name: Generate Envs profiles dir
  ansible.builtin.file:
    path: "{{ _current_env_dir }}/Profiles"
    state: directory

- name: Generate Envs Namespace yaml {{ _profile_template_name }} for {{ profile.name }}
  ansible.builtin.blockinfile:
    path: "{{ _current_env_dir }}/Profiles/{{ _profile_template_name }}.yml"
    block: "{{ lookup('template', profile.template_path) }}"
    create: yes
